name: Stock Data Collection

on:
  schedule:
    - cron: "0 * * * 1-5" # Runs every hour, Monday to Friday (1=Monday, 5=Friday)
  workflow_dispatch: # Allow manual trigger

jobs:
  collect-stock-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance psycopg2-binary python-dotenv

      - name: Run stock data collection
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python stock_collector.py
